package view;

 
import util.DataIO;
import model.Customer;
import enums.YardType;
import service.CustomerService;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rayk2
 */
public class LandscapeGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LandscapeGUI.class.getName());

    // class-level variables
    DefaultListModel<Customer> customerList;
    DefaultTableModel customerTableModel;
    private CustomerService service;
    
    /**
     * Creates new form LandscapeGUI
     */
    public LandscapeGUI() {
        
        // instantiate variables
        customerList = new DefaultListModel<>();
        customerTableModel = new DefaultTableModel();
        service = new CustomerService();
        
        initComponents();
        
        loadList();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgYardType = new javax.swing.ButtonGroup();
        tabMain = new javax.swing.JTabbedPane();
        pnlWelcome = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        rdoGrass = new javax.swing.JRadioButton();
        rdoGravel = new javax.swing.JRadioButton();
        lblIcon = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblYardType = new javax.swing.JLabel();
        lblGravel = new javax.swing.JLabel();
        lblGrass = new javax.swing.JLabel();
        pnlInformation = new javax.swing.JPanel();
        lblInfoTitle = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        lblInfoInput = new javax.swing.JLabel();
        lblOrderSummary = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        scrOrderSummery = new javax.swing.JScrollPane();
        txaOrder = new javax.swing.JTextArea();
        lblAddress = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        lblInfoInput1 = new javax.swing.JLabel();
        lblWidth = new javax.swing.JLabel();
        txtWidth = new javax.swing.JTextField();
        lblLength = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        pnlCustomerList = new javax.swing.JPanel();
        lblCustomerListTitle = new javax.swing.JLabel();
        lblCustomerDetails = new javax.swing.JLabel();
        scrCustomerDetails = new javax.swing.JScrollPane();
        txaCustomerDetails = new javax.swing.JTextArea();
        btnDelete = new javax.swing.JButton();
        lblCustomerList = new javax.swing.JLabel();
        scrCustomerList = new javax.swing.JScrollPane();
        lstCustomers = new javax.swing.JList<>();
        btnLoadList = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        pnlCustomerTable = new javax.swing.JPanel();
        lblCustomerTableTitle = new javax.swing.JLabel();
        lblCustomerTable = new javax.swing.JLabel();
        scrCustomerTable = new javax.swing.JScrollPane();
        tblCustomerTable = new javax.swing.JTable();
        btnSaveToCSV = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        mnbMainMenu = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        itemExit = new javax.swing.JMenuItem();
        mnuOrder = new javax.swing.JMenu();
        itemSubmitOrder = new javax.swing.JMenuItem();
        itemReset = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Landscape Management System");

        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(this::btnNextActionPerformed);

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        bgYardType.add(rdoGrass);
        rdoGrass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoGrass.setText("Grass");
        rdoGrass.addActionListener(this::rdoGrassActionPerformed);

        bgYardType.add(rdoGravel);
        rdoGravel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoGravel.setText("Gravel");
        rdoGravel.addActionListener(this::rdoGravelActionPerformed);

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dirt.jpg"))); // NOI18N

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWelcome.setText("Raymond Krajcsi Landscapes");

        lblYardType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblYardType.setText("Would you like a grass or gravel yard?");

        lblGravel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGravel.setText("$2 per sqft");

        lblGrass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGrass.setText("$5 per sqft");

        javax.swing.GroupLayout pnlWelcomeLayout = new javax.swing.GroupLayout(pnlWelcome);
        pnlWelcome.setLayout(pnlWelcomeLayout);
        pnlWelcomeLayout.setHorizontalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWelcomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoGrass)
                    .addComponent(lblGrass, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142)
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGravel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoGravel))
                .addGap(310, 310, 310))
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addGap(0, 199, Short.MAX_VALUE)
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWelcomeLayout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWelcomeLayout.createSequentialGroup()
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95))))
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(lblYardType)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlWelcomeLayout.setVerticalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addComponent(lblYardType)
                        .addGap(18, 18, 18)
                        .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoGrass)
                            .addComponent(rdoGravel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGravel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGrass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabMain.addTab("Welcome", pnlWelcome);

        pnlInformation.setName(""); // NOI18N

        lblInfoTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblInfoTitle.setText("Raymond Krajcsi Landscapes");

        btnCalculate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.setNextFocusableComponent(btnSubmit);
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        lblInfoInput.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInfoInput.setText("Please enter your information");

        lblOrderSummary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOrderSummary.setText("Order Summary:");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setText("Name:");

        txaOrder.setEditable(false);
        txaOrder.setColumns(20);
        txaOrder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txaOrder.setRows(5);
        scrOrderSummery.setViewportView(txaOrder);

        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAddress.setText("Address:");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtName.setNextFocusableComponent(txtAddress);

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSubmit.setText("Submit Order");
        btnSubmit.setNextFocusableComponent(txtName);
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddress.setNextFocusableComponent(txtWidth);

        lblInfoInput1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInfoInput1.setText("Enter length and width of your yard:");

        lblWidth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWidth.setText("Width (ft):");

        txtWidth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtWidth.setNextFocusableComponent(txtLength);

        lblLength.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLength.setText("Length (ft):");

        txtLength.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLength.setNextFocusableComponent(btnCalculate);

        javax.swing.GroupLayout pnlInformationLayout = new javax.swing.GroupLayout(pnlInformation);
        pnlInformation.setLayout(pnlInformationLayout);
        pnlInformationLayout.setHorizontalGroup(
            pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInformationLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblWidth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(lblLength)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInfoInput1)
                            .addGroup(pnlInformationLayout.createSequentialGroup()
                                .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInformationLayout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(scrOrderSummery, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addComponent(lblInfoInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOrderSummary)
                        .addGap(109, 109, 109)))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
            .addGroup(pnlInformationLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        pnlInformationLayout.setVerticalGroup(
            pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoInput)
                    .addComponent(lblOrderSummary))
                .addGap(18, 18, 18)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblInfoInput1)
                        .addGap(18, 18, 18)
                        .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblLength, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(scrOrderSummery))
                .addGap(27, 27, 27)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tabMain.addTab("Information", pnlInformation);

        lblCustomerListTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblCustomerListTitle.setText("Raymond Krajcsi Landscapes");

        lblCustomerDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCustomerDetails.setText("Customer Details");

        txaCustomerDetails.setEditable(false);
        txaCustomerDetails.setColumns(20);
        txaCustomerDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txaCustomerDetails.setRows(5);
        scrCustomerDetails.setViewportView(txaCustomerDetails);

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.setText("Delete Customer");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        lblCustomerList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCustomerList.setText("Customer List");

        lstCustomers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstCustomers.setModel(customerList);
        lstCustomers.addListSelectionListener(this::lstCustomersValueChanged);
        scrCustomerList.setViewportView(lstCustomers);

        btnLoadList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLoadList.setText("Load List");
        btnLoadList.addActionListener(this::btnLoadListActionPerformed);

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        javax.swing.GroupLayout pnlCustomerListLayout = new javax.swing.GroupLayout(pnlCustomerList);
        pnlCustomerList.setLayout(pnlCustomerListLayout);
        pnlCustomerListLayout.setHorizontalGroup(
            pnlCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerListLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCustomerListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
            .addGroup(pnlCustomerListLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(pnlCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCustomerListLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblCustomerList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCustomerDetails)
                        .addGap(208, 208, 208))
                    .addGroup(pnlCustomerListLayout.createSequentialGroup()
                        .addGroup(pnlCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCustomerListLayout.createSequentialGroup()
                                .addComponent(btnLoadList, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCustomerListLayout.createSequentialGroup()
                                .addComponent(scrCustomerList, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(scrCustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(132, Short.MAX_VALUE))))
        );
        pnlCustomerListLayout.setVerticalGroup(
            pnlCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerListLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCustomerListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerDetails)
                    .addComponent(lblCustomerList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrCustomerList)
                    .addComponent(scrCustomerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlCustomerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadList, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        tabMain.addTab("Customer List", pnlCustomerList);

        lblCustomerTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblCustomerTableTitle.setText("Raymond Krajcsi Landscapes");

        lblCustomerTable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCustomerTable.setText("Customer Table");

        tblCustomerTable.setModel(customerTableModel);
        scrCustomerTable.setViewportView(tblCustomerTable);

        btnSaveToCSV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSaveToCSV.setText("Save to CSV");
        btnSaveToCSV.addActionListener(this::btnSaveToCSVActionPerformed);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        javax.swing.GroupLayout pnlCustomerTableLayout = new javax.swing.GroupLayout(pnlCustomerTable);
        pnlCustomerTable.setLayout(pnlCustomerTableLayout);
        pnlCustomerTableLayout.setHorizontalGroup(
            pnlCustomerTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerTableLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(lblCustomerTableTitle)
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(pnlCustomerTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomerTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrCustomerTable, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCustomerTableLayout.createSequentialGroup()
                        .addGroup(pnlCustomerTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveToCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCustomerTableLayout.createSequentialGroup()
                                .addGroup(pnlCustomerTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch))
                                .addGap(208, 208, 208)
                                .addComponent(lblCustomerTable)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlCustomerTableLayout.setVerticalGroup(
            pnlCustomerTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerTableLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblCustomerTableTitle)
                .addGroup(pnlCustomerTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCustomerTableLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblCustomerTable))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerTableLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrCustomerTable, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveToCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tabMain.addTab("Customer Table", pnlCustomerTable);

        mnuFile.setText("File");

        itemExit.setText("Exit");
        itemExit.addActionListener(this::itemExitActionPerformed);
        mnuFile.add(itemExit);

        mnbMainMenu.add(mnuFile);

        mnuOrder.setText("Order");

        itemSubmitOrder.setText("Submit Order");
        itemSubmitOrder.addActionListener(this::itemSubmitOrderActionPerformed);
        mnuOrder.add(itemSubmitOrder);

        itemReset.setText("Reset");
        itemReset.addActionListener(this::itemResetActionPerformed);
        mnuOrder.add(itemReset);

        mnbMainMenu.add(mnuOrder);

        setJMenuBar(mnbMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        // exit the application
        System.exit(0);
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemSubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSubmitOrderActionPerformed
        submitOrder();
    }//GEN-LAST:event_itemSubmitOrderActionPerformed

    private void itemResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemResetActionPerformed
        // reset view and clear radio button selections
        reset();
    }//GEN-LAST:event_itemResetActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // verify radio button is selected
        if (rdoGrass.isSelected() == false && rdoGravel.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Yard type must be selected", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
            tabMain.setSelectedIndex(1);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void rdoGrassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGrassActionPerformed
        if (rdoGrass.isSelected()) {

            // get location of "grass.jpg"
            URL location = this.getClass().getResource("/images/grass.jpg");

            // create image icon object using location of "gravel.jpg"
            ImageIcon icon = new ImageIcon(location);

            // set icon on the icon lable
            lblIcon.setIcon(icon);
        }

    }//GEN-LAST:event_rdoGrassActionPerformed

    private void rdoGravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGravelActionPerformed

        if (rdoGravel.isSelected()) {

            lblIcon.setIcon(new ImageIcon(this.getClass().getResource("/images/gravel.jpg")));
        }
    }//GEN-LAST:event_rdoGravelActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // validate text fields
        if (!validateFields()) {
            return;
        }

        // create customer object
        Customer cust = createCustomer();

        // display customer details on text area
        txaOrder.setText(cust.getDetails());
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        submitOrder();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        // get the value of the customer selected from the JList
        Customer cust = lstCustomers.getSelectedValue();
        
        // ensure customer is selected before deleting
        if (cust == null) {
            JOptionPane.showMessageDialog(this, "Customer must be selected", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // get customers name
        int customerID = cust.getCustomerID();
        
        JOptionPane.showMessageDialog(this, "Customer: " + cust + " has been deleted with ID: " + customerID);
        
        // delete customer by name
        service.deleteCustomer(customerID);
        
        // clear customer details text area
        txaCustomerDetails.setText("");
        
        // re-load customer list
        loadList();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnLoadListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadListActionPerformed

        loadList();
    }//GEN-LAST:event_btnLoadListActionPerformed

    private void lstCustomersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCustomersValueChanged
        // get index of customer selected
        int index = lstCustomers.getSelectedIndex();
        
        // ensure customer was selected
        if (index != -1) {
            
            // get customer at the index selected
            Customer customer = customerList.getElementAt(index);
            
            // display customer on customer details text area
            txaCustomerDetails.setText(customer.getDetails());
        }
    }//GEN-LAST:event_lstCustomersValueChanged

    private void btnSaveToCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToCSVActionPerformed
        // get filename from customer
        String fileName = JOptionPane.showInputDialog(this, "Enter filename");
        
        // create DataIO object
        DataIO data = new DataIO();
        
        // create array list to hold customers from table model
        ArrayList<Customer> custList = new ArrayList<>();
        
        // get table model
        customerTableModel = (DefaultTableModel) tblCustomerTable.getModel();
        
        for (int i = 0; i < customerTableModel.getRowCount(); i++) {
            
            // extract data from table model
            int id = (Integer) customerTableModel.getValueAt(i, 0);
            String name = (String) customerTableModel.getValueAt(i, 1);
            String address = (String) customerTableModel.getValueAt(i, 2);
            YardType yardType = (YardType) customerTableModel.getValueAt(i, 3);
            double width = (Double) customerTableModel.getValueAt(i, 4);
            double length = (Double) customerTableModel.getValueAt(i, 5);
            double totalCost = (Double) customerTableModel.getValueAt(i, 6);
            
            // add fields to array list
            custList.add(new Customer(id, name, address, yardType, width, length, totalCost));
        }
        // pass customer list into save method from DataIO object
        boolean dataSaved = data.add(custList);
        
        if (dataSaved == true) {
            JOptionPane.showMessageDialog(this, "File successfully saved!");
        }
    }//GEN-LAST:event_btnSaveToCSVActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        // validate for empty text field
        if (txtSearch.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cannot be blank!");
            txtSearch.setText("");
            txtSearch.requestFocus();
            return;
        }
        
        // extract text from search text box
        String search = txtSearch.getText();

        // create array list to hold query results
        ArrayList<Customer> custList = new ArrayList<>();
        
        // search for customer by name or address and save results into array list
        custList = service.searchCustomerByNameOrAddress(search);
        
        // if results are empty, display message
        if (custList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No customers were found", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        // create columns for customer table model
        String[] columns = {"Customer ID", "Customer Name", "Address", "Yard Type", "Width", "Length", "Total Cost"};
        
        // set columns on table model
        customerTableModel = new DefaultTableModel(columns, 0);
        
        // iterate through array list
        for (Customer cust : custList) {
            
            // create rows for each customer
            Object[] rows = {
                cust.getCustomerID(),
                cust.getName(),
                cust.getAddress(),
                cust.getYardType(),
                cust.getWidth(),
                cust.getLength(),
                cust.getTotalCost()
            };
            // set rows on table model
            customerTableModel.addRow(rows);
        }
        // set table model on JTable to make it visible
        tblCustomerTable.setModel(customerTableModel);
        
        // clear text field for next search
        txtSearch.setText("");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        JOptionPane.showMessageDialog(this, "Method not yet implemented"); 
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LandscapeGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgYardType;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLoadList;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSaveToCSV;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemReset;
    private javax.swing.JMenuItem itemSubmitOrder;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCustomerDetails;
    private javax.swing.JLabel lblCustomerList;
    private javax.swing.JLabel lblCustomerListTitle;
    private javax.swing.JLabel lblCustomerTable;
    private javax.swing.JLabel lblCustomerTableTitle;
    private javax.swing.JLabel lblGrass;
    private javax.swing.JLabel lblGravel;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblInfoInput;
    private javax.swing.JLabel lblInfoInput1;
    private javax.swing.JLabel lblInfoTitle;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrderSummary;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JLabel lblYardType;
    private javax.swing.JList<Customer> lstCustomers;
    private javax.swing.JMenuBar mnbMainMenu;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuOrder;
    private javax.swing.JPanel pnlCustomerList;
    private javax.swing.JPanel pnlCustomerTable;
    private javax.swing.JPanel pnlInformation;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JRadioButton rdoGrass;
    private javax.swing.JRadioButton rdoGravel;
    private javax.swing.JScrollPane scrCustomerDetails;
    private javax.swing.JScrollPane scrCustomerList;
    private javax.swing.JScrollPane scrCustomerTable;
    private javax.swing.JScrollPane scrOrderSummery;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTable tblCustomerTable;
    private javax.swing.JTextArea txaCustomerDetails;
    private javax.swing.JTextArea txaOrder;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        // go back to first frame
        tabMain.setSelectedIndex(0);

        // reset radio button group so none are selected
        bgYardType.clearSelection();
        
        // set default icon to dirt
        lblIcon.setIcon(new ImageIcon(getClass().getResource("/images/dirt.jpg")));
        
        // set text fields and order text area to empty
        txtName.setText("");
        this.txtName.requestFocusInWindow();
        txtAddress.setText("");
        txtWidth.setText("");
        txtLength.setText("");
        txaOrder.setText("");
        
    }

    private boolean validateFields() {
        
        // verify radio button is selected
        if (bgYardType.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Yard type is required", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        // verify text fields are not empty
        JTextField[] fields = {txtName, txtAddress, txtWidth, txtLength};
        String[] names = {"Name", "Address", "Width", "Length"};
        
        for (int i = 0; i < fields.length; i++) {
            if (fields[i].getText().isEmpty()) {
                showError(names[i] + " is required", fields[i]);
                return false;
            }
        }
        
        // verify name contains only letters
        if (txtName.getText().matches(".*[^A-Za-z ].*")) {
            JOptionPane.showMessageDialog(this, "Name must be characters", "Error", JOptionPane.ERROR_MESSAGE);
            txtName.setText("");
            txtName.requestFocus();
            return false;
        }
        
        // validate that width and length are postive numbers or decimals
        JTextField[] jFields = {txtWidth, txtLength};
        String[] jNames = {"Width", "Length"};
        
        for (int i = 0; i < jFields.length; i++) {
            
            // get text from fields
            String field = jFields[i].getText().trim(); // trim removes leading and trailing spaces
            
            if (!field.matches("\\d+(\\.\\d+)?")) {
                showError(jNames[i] + " must be numeric or decimal", jFields[i]);
                return false;
            }
        }
        
        // check if address is greater than 5 characters
        if (txtAddress.getText().length() <= 5) {
            JOptionPane.showMessageDialog(this, "Address must be greater than 5 characters", "Error", JOptionPane.ERROR_MESSAGE);
            txtAddress.setText("");
            txtAddress.requestFocusInWindow();
            return false;
        }
        
        // verfiy that width and length are greater than 0
        if (Double.parseDouble(txtWidth.getText()) <= 0) {
            JOptionPane.showMessageDialog(this, "Width must be greater than 0", "Error", JOptionPane.ERROR_MESSAGE);
            txtWidth.setText("");
            txtWidth.requestFocusInWindow();
            return false;
        }
        
        // verfiy that width and length are greater than 0
        if (Double.parseDouble(txtLength.getText()) <= 0) {
            JOptionPane.showMessageDialog(this, "Length must be greater than 0", "Error", JOptionPane.ERROR_MESSAGE);
            txtLength.setText("");
            txtLength.requestFocusInWindow();
            return false;
        }
        
        // verify that width and length are numeric
        try {
            double width = Double.parseDouble(txtWidth.getText());
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Width must be numeric", "Error", JOptionPane.ERROR_MESSAGE);
            txtWidth.setText("");
            txtWidth.requestFocusInWindow();
            return false;
        }
        
        // verify that width and length are numeric
        try {
            double length = Double.parseDouble(txtLength.getText());
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Length must be numeric", "Error", JOptionPane.ERROR_MESSAGE);
            txtLength.setText("");
            txtLength.requestFocusInWindow();
            return false;
        }
        
        return true;
    }

    private void showError(String message, JTextField field) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        field.setText("");
        field.requestFocusInWindow();
    }

    private Customer createCustomer() {
        // extract data from text fields
        String name = txtName.getText();
        String address = txtAddress.getText();
        YardType yardType = null;
        double width = Double.parseDouble(txtWidth.getText());
        double length = Double.parseDouble(txtLength.getText());
        double totalCost = 0.0;
        
        
        if (rdoGrass.isSelected()) {
            yardType = YardType.GRASS;
            totalCost = service.calculateTotalCost(yardType, width, length);
        }
        else if (rdoGravel.isSelected()) {
            yardType = YardType.GRAVEL;
            totalCost = service.calculateTotalCost(yardType, width, length);
        }
        else {
            JOptionPane.showMessageDialog(this, "Yard type is required", "Error", JOptionPane.ERROR_MESSAGE);
            totalCost = 0.0;
        }
        
        // create customer object
        Customer cust = new Customer(0, name, address, yardType, width, length, totalCost);
        
        // return customer
        return cust;
    }

    private void submitOrder() {
        // validate text fields
        if (!validateFields()) {
            return;
        }
        
        // create customer
        Customer cust = createCustomer();
        
        // add customer
        service.addCustomer(cust);
        
        // load latest customer list
        loadList();
        
        // reset form for next customer
        reset();
            
        // move to next tab
        tabMain.setSelectedIndex(2); 
    }

    private void loadList() {
        // pull query results from DB info into array list
        ArrayList<Customer> custList = service.getAllCustomers();
        
        // clear model list
        customerList.clear();
        
        // clear customer text area
        txaCustomerDetails.setText("");
        
        // iterate through customer array list and add element to list model
        for (Customer cust : custList) {
            customerList.addElement(cust);
        }
        
        // displaying customer list on JTable
        // create columns for table model
        String[] columns = {"Customer ID", "Customer Name", "Address", "Yard Type", "Width", "Length", "Total Cost"};
        
        // set columns on table model
        customerTableModel = new DefaultTableModel(columns, 0);
        
        // iterate through customer list array and create rows of table model
        for (Customer cust : custList) {
            
            // create rows
            Object[] rows = new Object[] {
                cust.getCustomerID(),
                cust.getName(),
                cust.getAddress(),
                cust.getYardType(),
                cust.getWidth(),
                cust.getLength(),
                cust.getTotalCost()
            };
            // add rows to table model
            customerTableModel.addRow(rows);
        }
        // set customer table model as model on JTable
        tblCustomerTable.setModel(customerTableModel);
    }
}
